import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const colors = {
  primary: '#000000',
  secondary: '#757575',
  background: '#FFFFFF',
  text: '#000000',
  textSecondary: '#757575',
  border: '#E0E0E0',
  error: '#D32F2F',
  success: '#2E7D32',
  inputBg: '#F8F9FA',
  subtle: '#F1F3F5',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  formContainer: {
    flex: 1,
    padding: 24,
    justifyContent: 'flex-start',
    paddingTop: 80,
  },
  appTitle: {
    fontSize: 38,
    fontFamily: 'System',
    fontWeight: '900',
    color: colors.primary,
    textAlign: 'left',
    marginBottom: 12,
    letterSpacing: 1,
    paddingHorizontal: 4,
  },
  appSubtitle: {
    fontSize: 17,
    fontFamily: 'System',
    color: colors.textSecondary,
    textAlign: 'left',
    marginBottom: 56,
    letterSpacing: 0.3,
    lineHeight: 24,
    paddingHorizontal: 4,
  },
  title: {
    fontSize: 28,
    fontFamily: 'System',
    fontWeight: '700',
    color: colors.text,
    textAlign: 'left',
    marginBottom: 12,
    letterSpacing: 0.5,
    paddingHorizontal: 4,
  },
  subtitle: {
    fontSize: 16,
    fontFamily: 'System',
    color: colors.textSecondary,
    textAlign: 'left',
    marginBottom: 40,
    lineHeight: 24,
    letterSpacing: 0.2,
    paddingHorizontal: 4,
  },
  input: {
    height: 60,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 16,
    paddingHorizontal: 20,
    fontSize: 16,
    fontFamily: 'System',
    backgroundColor: colors.inputBg,
    marginBottom: 20,
    color: colors.text,
  },
  inputFocused: {
    borderColor: colors.primary,
    borderWidth: 2,
    backgroundColor: colors.background,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  button: {
    height: 58,
    backgroundColor: colors.primary,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonText: {
    color: colors.background,
    fontSize: 17,
    fontFamily: 'System',
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  linkButton: {
    marginTop: 28,
    alignItems: 'center',
    padding: 12,
  },
  linkText: {
    color: colors.primary,
    fontSize: 16,
    fontFamily: 'System',
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  errorText: {
    color: colors.error,
    fontSize: 14,
    fontFamily: 'System',
    marginTop: -16,
    marginBottom: 16,
    paddingLeft: 4,
  },
  phoneInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  phonePrefix: {
    fontSize: 16,
    fontFamily: 'System',
    backgroundColor: colors.subtle,
    paddingHorizontal: 18,
    paddingVertical: 17,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 16,
    marginRight: 12,
    color: colors.text,
    fontWeight: '600',
  },
  phoneInput: {
    flex: 1,
    marginBottom: 0,
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 40,
    paddingHorizontal: 4,
  },
  otpInput: {
    width: (width - 96) / 6,
    height: 60,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 16,
    fontSize: 24,
    fontFamily: 'System',
    textAlign: 'center',
    backgroundColor: colors.inputBg,
    color: colors.text,
  },
  otpInputFocused: {
    borderColor: colors.primary,
    borderWidth: 2,
    backgroundColor: colors.background,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  formSection: {
    marginBottom: 36,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 36,
  },
});

export { styles as globalStyles };
export default styles; 